version: '2.1'
services:
  pub:
    hostname: pub
    container_name: pub
    image: locksmithdon/ssb-tutorial
    command: /scuttlebot/${PUB_ACTION-run}-server.sh
    environment:
      SSB_SERVER_PORT: 8118
      SSB_DEBUG_PORT: 9119
      SSB_HOST: pub
    volumes:
      - ./shared:/shared
    ports:
      - "8118:8118"
      - "9119:9119"
  user1:
    hostname: user1
    container_name: user1
    image: locksmithdon/ssb-tutorial
    command: /scuttlebot/${USER1_ACTION-run}-server.sh
    environment:
      SSB_SERVER_PORT: 8228
      SSB_DEBUG_PORT: 9229
      SSB_HOST: user1
    volumes:
      - ./shared:/shared
    ports:
      - "8228:8228"
      - "9229:9229"
  user2:
    hostname: user2
    container_name: user2
    image: locksmithdon/ssb-tutorial
    command: /scuttlebot/${USER2_ACTION-run}-server.sh
    environment:
      SSB_SERVER_PORT: 8338
      SSB_DEBUG_PORT: 9339
      SSB_HOST: user2
    volumes:
      - ./shared:/shared
    ports:
      - "8338:8338"
      - "9339:9339"
